_wandb:
    value:
        cli_version: 0.25.0
        e:
            u73xsqlx4p16j83aqibn8lbbdar7re37:
                codePath: weight_init_analysis.py
                codePathLocal: weight_init_analysis.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "195628625920"
                        used: "186434502656"
                email: da25m006@smail.iitm.ac.in
                executable: C:\Users\HP\ds_env\Scripts\python.exe
                host: Ajaz
                memory:
                    total: "16936132608"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Downloads\file\weight_init_analysis.py
                python: CPython 3.12.10
                root: C:\Users\HP\Downloads\file
                startedAt: "2026-02-27T05:18:26.570589Z"
                writerId: u73xsqlx4p16j83aqibn8lbbdar7re37
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.10
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 5
hidden_sizes:
    value:
        - 128
        - 64
label:
    value: xavier-init
learning_rate:
    value: 0.01
loss:
    value: cross_entropy
monitor_layer:
    value: 0
monitor_neurons:
    value:
        - 0
        - 1
        - 2
        - 3
        - 4
optimizer:
    value: sgd
wandb_project:
    value: da6401-assignment1
weight_decay:
    value: 0
weight_init:
    value: xavier
