_wandb:
    value:
        cli_version: 0.25.0
        e:
            9vgqdz0su5b05w35dyawmesxvyc7u0h7:
                codePath: fashion_mnist_transfer.py
                codePathLocal: fashion_mnist_transfer.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "195628625920"
                        used: "185872617472"
                email: da25m006@smail.iitm.ac.in
                executable: C:\Users\HP\ds_env\Scripts\python.exe
                host: Ajaz
                memory:
                    total: "16936132608"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Downloads\file\fashion_mnist_transfer.py
                python: CPython 3.12.10
                root: C:\Users\HP\Downloads\file
                startedAt: "2026-02-26T11:08:13.474880Z"
                writerId: 9vgqdz0su5b05w35dyawmesxvyc7u0h7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.10
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 20
hidden_sizes:
    value:
        - 128
        - 128
        - 128
label:
    value: config-1-adam-relu
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
optimizer:
    value: adam
wandb_project:
    value: da6401-assignment1
weight_decay:
    value: 0
weight_init:
    value: xavier
