_wandb:
    value:
        cli_version: 0.25.0
        e:
            2h13ruvn8xem15lq9iqd2rf1j8lqu8i1:
                codePath: dead_neuron.py
                codePathLocal: dead_neuron.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "195628625920"
                        used: "185856442368"
                email: da25m006@smail.iitm.ac.in
                executable: C:\Users\HP\ds_env\Scripts\python.exe
                host: Ajaz
                memory:
                    total: "16936132608"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Downloads\file\dead_neuron.py
                python: CPython 3.12.10
                root: C:\Users\HP\Downloads\file
                startedAt: "2026-02-26T11:06:50.531738Z"
                writerId: 2h13ruvn8xem15lq9iqd2rf1j8lqu8i1
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.10
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 15
hidden_sizes:
    value:
        - 128
        - 128
        - 128
label:
    value: tanh-normal-lr
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
optimizer:
    value: sgd
wandb_project:
    value: da6401-assignment1
weight_decay:
    value: 0
weight_init:
    value: xavier
