_wandb:
    value:
        cli_version: 0.25.0
        e:
            v8q70z7lwzb0rw9lz268ss4mggzlpa1a:
                args:
                    - --model
                    - best_model.npy
                    - --config
                    - best_config.json
                codePath: confusion_matrix.py
                codePathLocal: confusion_matrix.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "195628625920"
                        used: "185236672512"
                email: da25m006@smail.iitm.ac.in
                executable: C:\Users\HP\ds_env\Scripts\python.exe
                host: Ajaz
                memory:
                    total: "16936132608"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Downloads\file\confusion_matrix.py
                python: CPython 3.12.10
                root: C:\Users\HP\Downloads\file
                startedAt: "2026-02-26T10:41:54.874915Z"
                writerId: v8q70z7lwzb0rw9lz268ss4mggzlpa1a
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 62
            "4": 3.12.10
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
        visualize:
            confusion_matrix_wandb:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_wandb_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
